# Generated by Django 5.1.6 on 2025-03-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyFlow', '0003_transactions_amount_transactions_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='moneyFlow.type', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='moneyFlow.category', verbose_name='Подкатегория'),
        ),
    ]
