# Generated by Django 5.1.6 on 2025-03-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyFlow', '0008_remove_subcategory_category_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='moneyFlow.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
